version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=mykadri
      - MONGO_COLLECTION=movies

  mongo:
    image: mongo:6
    container_name: mykadri-mongo

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

